# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_auto_20160710_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('players_num', models.PositiveSmallIntegerField()),
                ('type', models.TextField()),
                ('winner', models.TextField()),
                ('status', models.TextField(default='Created')),
                ('created_by', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.ChatRoom')),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
