# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20160716_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
